{{- if not .Values.csi.enable }}

{{- if .Values.pspEnabled -}}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "storageos.fullname" . }}-psp
  namespace: {{ .Values.namespace }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - 'SYS_ADMIN'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 5700
    max: 5800
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "storageos.fullname" . }}-psp-user
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ template "storageos.fullname" . }}-psp
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ template "storageos.fullname" . }}-psp-user
    namespace: {{ .Values.namespace }}
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: Role
   name: {{ template "storageos.fullname" . }}-psp-user
subjects:
- kind: ServiceAccount
  name: {{ template "storageos.fullname" . }}
  namespace: {{ .Values.namespace }}
{{- end -}}

{{- end }}
